### ISSUE TITLE
Can not insert record if the the varlue is very long

### ISSUE THREAD

**Issue by topikachu** [jenkinsci/junit-sql-storage-plugin#264]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins in container
Controller:
jenkins/jenkins:2.361.4-jdk11
Agent:
jenkins/inbound-agent:4.11.2-4

Postgres:
PostgreSQL 13.6 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 7.4.0, 64-bit

### Reproduction steps

Run a maven test which causes a very long stack trace.

### Expected Results

No error and the test result is inserted in the database

### Actual Results

```
ERROR: [withMaven] WARNING Exception executing Maven reporter 'Junit Publisher' / org.jenkinsci.plugins.pipeline.maven.publishers.JunitTestsPublisher. Please report a bug associated for the component 'pipeline-maven-plugin' at https://issues.jenkins-ci.org/ 
 hudson.remoting.ProxyException: java.io.IOException: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100000)
```

### Anything else?

I can file a fix but I'd like to know the design.
Shall we increase the varchar size or use text type instead of?
Or truncate the long text to the right size?

**Comment by timja** [comment]
unsure open to either fix but I don't think we want it to be unlimited, so we can probably just truncate to the before the maximum limit if that works
