### ISSUE TITLE
View of test results per job

### ISSUE THREAD

**Issue by reitzmichnicht** [jenkinsci/junit-sql-storage-plugin#40]
I tried this new feature with jenkins lts 2.263.1 and postgres DB.
It did not migrate any old data to the database, so only new runs show up on the job test chart. But if I click on the jobs test result menu entry only the number of tests is shown on top, but the list of test classes is empty.

Is this supposed to work yet?

**Comment by timja** [comment]
Hey,

There's no migration functionality yet,
As far as I know test results should all work except the history table,

Which is tracked here:
https://github.com/jenkinsci/junit-plugin/issues/165

If it's not the history table a bit more detail will be great and i'll try find some time to take a look

**Comment by 2012ucp1544** [comment]
Also facing the same issue.

1. While running using this plugin Count of number of test failures is displayed but not the actual test information which get failed.
![image](https://user-images.githubusercontent.com/68544865/102111908-fb5cac00-3e5c-11eb-9ced-af00a97e3c46.png)
![image](https://user-images.githubusercontent.com/68544865/102111942-057eaa80-3e5d-11eb-83b2-9370a605b8d3.png)

2.While executing junit tests without using this plugin.
![image](https://user-images.githubusercontent.com/68544865/102112051-2b0bb400-3e5d-11eb-8429-c65478061fcb.png)
![image](https://user-images.githubusercontent.com/68544865/102112081-36f77600-3e5d-11eb-87c5-182e9876a570.png)

**Comment by timja** [comment]
Hmm this worked last time I checked, will take a look

**Comment by 2012ucp1544** [comment]
Yes it is working now.
Earlier i tried and faced issue with released verison : 0.2
@timja Could you please release version : 0.3 , as it is not available on maven repository.That would be very helpful.
Also please feel free to close the issue after releasing 0.3 on maven repository.
I tried explicitly by downloading from [1], then it worked out.

[1] : https://mvnrepository.com/artifact/io.jenkins.plugins/junit-sql-storage/0.3-rc37.260f0de0c4a1

**Comment by timja** [comment]
Looks like there must have been an issue with releasing it

I've just re-released 0.3, https://github.com/jenkinsci/junit-sql-storage-plugin/releases/tag/junit-sql-storage-0.3

**Comment by 2012ucp1544** [comment]
@timja This is still not present on https://mvnrepository.com/artifact/io.jenkins.plugins/junit-sql-storage?repo=jenkins-releases
Could you please look into this?

**Comment by timja** [comment]
It's present here:
https://repo.jenkins-ci.org/releases/io/jenkins/plugins/junit-sql-storage/

I think that view is synced ~weekly

**Comment by 2012ucp1544** [comment]
Ok thanks, will wait for the week time :) 
Thanks for releasing.
