### ISSUE TITLE
Add tracing, logging, and caching to the plugin 

### ISSUE THREAD

**Issue by craigtmoore** [jenkinsci/junit-sql-storage-plugin#412]
### What feature do you want to see added?

In order to measure the performance of the plugin when accessing the database, we should add open telemetry tracing and logging. In addition, there are opportunities to introduce caching so that the plugin doesn't have to access the database each time it needs to access data. instead it can store the data temporarily in a cache to improve access times.

### Are you interested in contributing this feature?

yes, I plan to create a pull request soon to facilitate these changes.

**Comment by cyrille-leclerc** [comment]
@craigtmoore @timja FYI we are introducing an opentelemetry-api plugin to cleanup your dependencies:

* https://github.com/jenkins-infra/repository-permissions-updater/issues/3973

I also proposed an enhancement of the SQL spans:

* https://github.com/jenkinsci/junit-sql-storage-plugin/pull/416

cc @kuisathaverat
