### ISSUE TITLE
Inclusion of timestamp column in the caseresults table schema

### ISSUE THREAD

**Issue by 2012ucp1544** [jenkinsci/junit-sql-storage-plugin#46]
@timja 
It would be quite helpful, if we could include timestamp column in **Caseresults** table, as this could be leveraged, in the cleanup of entries which are older than a particular threshold.
Otherwise there would be table keep on populating database, without ant cleanup.

IMO inclusion of this file, should do : 
[V2020_12_15_1153__initial-schema.txt](https://github.com/jenkinsci/junit-sql-storage-plugin/files/5694055/V2020_12_15_1153__initial-schema.txt)

Can i raise a PR, as this is a very small change, so could be made faster.

**Comment by timja** [comment]
Please do raise a PR

**Comment by 2012ucp1544** [comment]
PR is merged, could we please review and close this issue?
cc : @timja

**Comment by timja** [comment]
https://github.com/jenkinsci/junit-sql-storage-plugin/releases/tag/junit-sql-storage-0.4
