### ISSUE TITLE
Support for MYSQL Database

### ISSUE THREAD

**Issue by 2012ucp1544** [jenkinsci/junit-sql-storage-plugin#48]
Current plugin supports postgres SQL Database and works fine with the migration scripts provided.
But does not work with MYSQL Database, as current sql scripts are not compatible.

Issues faced : 

1. **java.sql.SQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535**    reference -> https://stackoverflow.com/questions/13283381/row-size-too-large-error-in-mysql-create-table-query
2. ALTER scripts also do not work, as syntax is different.

**Comment by timja** [comment]
contributions welcome,
I assume we need a set of scripts for each support RDMS and then flyway to pick the right one

**Comment by 2012ucp1544** [comment]
[V2020_09_21_2052__initial-schema.txt](https://github.com/jenkinsci/junit-sql-storage-plugin/files/5702424/V2020_09_21_2052__initial-schema.txt)
[V2020_09_24_0900__initial-schema.txt](https://github.com/jenkinsci/junit-sql-storage-plugin/files/5702425/V2020_09_24_0900__initial-schema.txt)
[V2020_12_12_2000__longer-columns.txt](https://github.com/jenkinsci/junit-sql-storage-plugin/files/5702426/V2020_12_12_2000__longer-columns.txt)
[V2020_09_22_0802__indexes.txt](https://github.com/jenkinsci/junit-sql-storage-plugin/files/5702427/V2020_09_22_0802__indexes.txt)
[V2020_12_15_1153__timestamp-inclusion.txt](https://github.com/jenkinsci/junit-sql-storage-plugin/files/5702428/V2020_12_15_1153__timestamp-inclusion.txt)

I have made changes in SQL scripts as in, @timja would you be able to make changes for the flyway to pick these scripts ?

**Comment by timja** [comment]
yes that would be appreciated, 

as it's for a new DB type you should be able to do it in one SQL script

**Comment by 2012ucp1544** [comment]
> yes that would be appreciated,
> 
> as it's for a new DB type you should be able to do it in one SQL script

Yes right could be condensed in a single script, would you be able to pick this flyway part , i think there can be changes in UI as well where user can specify the database as well from UI(provide a dropdown), based on which flyway can make decision which script to execute.

**Comment by timja** [comment]
yes I can do that

**Comment by 2012ucp1544** [comment]
> yes I can do that

This would be a great help, as this will be first step to make this plugin truly generic :) 
Waiting for release from your side 👍

**Comment by timja** [comment]
This should work for you to test it out: https://github.com/jenkinsci/junit-sql-storage-plugin/pull/49

hardcoded to mysql for now, I'll finish it later
